apiVersion: v1
kind: Service
metadata:
  name: httpd-service # The name of the service
spec:
  type: NodePort # Specifies that this service is of type ClusterIP
  ports:
    - protocol: TCP
      port: 80 # The port that the service exposes
      targetPort: 80 # The target port on the container to send traffic to
      nodePort: 31708 