apiVersion: apps/v1
kind: Deployment # Specifies that this is a Kubernetes deployment object
metadata:
  labels:
    app: httpd
  name: httpd
spec:
  replicas: 2 # Specifies that two instances of the Apache HTTP Server should be created
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd # Specifies the name of the offical Apache HTTP Server image.
        name: httpd # Specifies the name of the Apache HTTP Server image container